"use client";

import { useCallback, useEffect, useMemo, useRef, useState, useSyncExternalStore } from "react";
import Link from "next/link";
import { AppShell } from "@/components/AppShell";
import { DateSwitcher } from "@/components/DateSwitcher";
import { useSelectedDate } from "@/components/SelectedDateProvider";
import { MealCard } from "@/components/meal/MealCard";
import { MealEditor } from "@/components/meal/MealEditor";
import { useMeals } from "@/components/meal/useMeals";
import { useProfile } from "@/components/profile/useProfile";
import { MealIcon, PlusIcon, UserIcon } from "@/components/icons";
import { compressGeneratedMealImageToDataUrl } from "@/lib/image";
import { mealImagePromptText, resolveMealCardImage } from "@/lib/mealCardImage";
import {
  generateMealImageOnce,
  getMealImageGenerationSnapshot,
  hasAnyPendingMealImageGeneration,
  hasPendingMealImageGeneration,
  runMealImageApplicationOnce,
  subscribeMealImageGenerationJobs,
} from "@/lib/mealImageGenerationJob";
import { deletePhoto, putPhoto } from "@/lib/photoStore";
import { loadMeals, saveMeals } from "@/lib/storage";
import { DATA_CHANGED_EVENT } from "@/lib/syncData";
import type { Meal } from "@/lib/types";

const MAX_AUTO_IMAGE_GENERATIONS_PER_SESSION = 12;
type MealImageGenerationOutcome = "saved" | "data-url-failed" | "stale";

export default function MealPage() {
  const { date, setDate } = useSelectedDate();
  const { dayMeals, ready, addMeal, updateMeal, removeMeal } = useMeals(date);
  const { profile, ready: profileReady } = useProfile();

  // null = closed, "new" = adding, Meal = editing.
  const [editorState, setEditorState] = useState<"new" | Meal | null>(null);
  const [generatingImageIds, setGeneratingImageIds] = useState<Set<string>>(() => new Set());
  const [imageErrorIds, setImageErrorIds] = useState<Set<string>>(() => new Set());
  const generatingImageIdsRef = useRef<Set<string>>(new Set());
  const mountedRef = useRef(true);
  const autoFailedImageKeysRef = useRef<Set<string>>(new Set());
  const autoGeneratedImageCountRef = useRef(0);
  const imageJobSnapshot = useSyncExternalStore(
    subscribeMealImageGenerationJobs,
    getMealImageGenerationSnapshot,
    () => 0,
  );

  useEffect(() => {
    mountedRef.current = true;
    return () => {
      mountedRef.current = false;
    };
  }, []);

  const setMealImageGenerating = useCallback((mealId: string, generating: boolean) => {
    const next = new Set(generatingImageIdsRef.current);
    if (generating) next.add(mealId);
    else next.delete(mealId);
    generatingImageIdsRef.current = next;
    if (mountedRef.current) setGeneratingImageIds(next);
  }, []);

  const setMealImageError = useCallback((mealId: string, hasError: boolean) => {
    if (!mountedRef.current) return;
    setImageErrorIds((current) => {
      const next = new Set(current);
      if (hasError) next.add(mealId);
      else next.delete(mealId);
      return next;
    });
  }, []);

  function handleSave(meal: Meal) {
    if (editorState === "new") addMeal(meal);
    else updateMeal(meal.id, meal);
    setEditorState(null);
  }

  // 「食べた」 (AIプランナー 第3陣D, the twin of the workout 完了): flip a PLANNED meal
  // to eaten so it starts counting toward 摂取/PFC/達成. Reuses the existing updateMeal
  // (tombstone-safe sync) — we only change the status, leaving the grounded
  // nutrition/items/recipe untouched.
  function handleEat(meal: Meal) {
    updateMeal(meal.id, { status: "eaten", updatedAt: new Date().toISOString() });
  }

  const updateGeneratedImageIfCurrent = useCallback(
    (mealId: string, promptText: string, patch: Partial<Meal>) => {
      let didApply = false;
      const nextMeals = loadMeals().map((candidate) => {
        if (candidate.id !== mealId) return candidate;
        if (mealImagePromptText(candidate) !== promptText) return candidate;
        didApply = true;
        return { ...candidate, ...patch };
      });
      if (!didApply) return false;
      saveMeals(nextMeals);
      window.dispatchEvent(new Event(DATA_CHANGED_EVENT));
      return true;
    },
    [],
  );

  const handleGenerateImage = useCallback(
    async (meal: Meal, options: { auto?: boolean } = {}) => {
      const promptText = mealImagePromptText(meal);
      if (!promptText) return;
      if (generatingImageIdsRef.current.has(meal.id)) return;

      const autoKey = `${meal.id}:${promptText}`;
      if (options.auto && hasAnyPendingMealImageGeneration()) return;
      if (options.auto && autoFailedImageKeysRef.current.has(autoKey)) return;
      if (
        options.auto &&
        autoGeneratedImageCountRef.current >= MAX_AUTO_IMAGE_GENERATIONS_PER_SESSION
      ) {
        return;
      }

      setMealImageGenerating(meal.id, true);
      setMealImageError(meal.id, false);
      try {
        const outcome = await runMealImageApplicationOnce<MealImageGenerationOutcome>(
          { mealId: meal.id, promptText },
          async () => {
            if (options.auto) autoGeneratedImageCountRef.current += 1;
            const blob = await generateMealImageOnce({ text: promptText });
            const id = `generated-meal-${meal.id}-${Date.now()}`;
            const generatedImageDataUrl = await compressGeneratedMealImageToDataUrl(blob);
            let generatedImageId: string | undefined = id;
            try {
              await putPhoto(id, blob);
            } catch {
              generatedImageId = undefined;
            }
            const didApply = updateGeneratedImageIfCurrent(meal.id, promptText, {
              generatedImageId,
              generatedImagePrompt: promptText,
              generatedImageDataUrl: generatedImageDataUrl ?? undefined,
              generatedImageDataUrlFailedPrompt: generatedImageDataUrl ? undefined : promptText,
              updatedAt: new Date().toISOString(),
            });
            if (!didApply) {
              if (generatedImageId) await deletePhoto(generatedImageId).catch(() => undefined);
              return "stale";
            }
            return generatedImageDataUrl ? "saved" : "data-url-failed";
          },
        );
        if (outcome === "saved") {
          autoFailedImageKeysRef.current.delete(autoKey);
          setMealImageError(meal.id, false);
        } else if (outcome === "data-url-failed") {
          if (options.auto) autoFailedImageKeysRef.current.add(autoKey);
          if (!options.auto) setMealImageError(meal.id, true);
        }
      } catch {
        if (options.auto) autoFailedImageKeysRef.current.add(autoKey);
        updateGeneratedImageIfCurrent(meal.id, promptText, {
          generatedImageDataUrlFailedPrompt: promptText,
          updatedAt: new Date().toISOString(),
        });
        if (!options.auto) setMealImageError(meal.id, true);
      } finally {
        setMealImageGenerating(meal.id, false);
      }
    },
    [setMealImageError, setMealImageGenerating, updateGeneratedImageIfCurrent],
  );

  const nextAutoImageMeal = useMemo(() => {
    if (
      !ready ||
      generatingImageIds.size > 0 ||
      hasAnyPendingMealImageGeneration() ||
      autoGeneratedImageCountRef.current >= MAX_AUTO_IMAGE_GENERATIONS_PER_SESSION
    ) {
      return null;
    }
    // Generate the NEWEST eligible meal's image FIRST. dayMeals is oldest-first, so
    // a plain find() served the oldest meal first and the meal the user JUST added
    // (sorted last) waited longest for its image. Scanning newest-first prioritizes
    // the just-added meal. Selection ORDER only — server concurrency is unchanged.
    const isEligible = (meal: Meal): boolean => {
      const imagePlan = resolveMealCardImage(meal);
      if (!imagePlan.needsAutoGeneratedImage) return false;
      if (hasPendingMealImageGeneration(imagePlan.promptText)) return false;
      return !autoFailedImageKeysRef.current.has(`${meal.id}:${imagePlan.promptText}`);
    };
    for (let i = dayMeals.length - 1; i >= 0; i--) {
      if (isEligible(dayMeals[i])) return dayMeals[i];
    }
    return null;
  }, [dayMeals, generatingImageIds, imageJobSnapshot, ready]);

  useEffect(() => {
    if (!nextAutoImageMeal || generatingImageIds.size > 0) return;
    void handleGenerateImage(nextAutoImageMeal, { auto: true });
  }, [generatingImageIds, handleGenerateImage, imageJobSnapshot, nextAutoImageMeal]);

  return (
    <AppShell>
      <div className="space-y-4 pb-24">
        {/* Page identity — 食事 = brand green (service colour). */}
        <header className="flex items-center gap-3">
          <span className="icon-chip bg-accent-100 text-accent-700 dark:bg-accent-light/15 dark:text-accent-light">
            <MealIcon className="h-5 w-5" />
          </span>
          <div className="min-w-0">
            <h1 className="text-lg font-bold tracking-tight">食事</h1>
            <p className="text-xs text-slate-500 dark:text-navy-300">
              ＋から写真かテキストで記録 → ✨AI解析でカロリーとPFC
            </p>
          </div>
        </header>

        <DateSwitcher date={date} onChange={setDate} />

        {profileReady && !profile && (
          <Link
            href="/profile"
            className="group flex items-center gap-3 rounded-2xl border border-accent/30 bg-accent/5 p-3.5 transition duration-200 ease-spring hover:-translate-y-0.5 hover:border-accent/50 hover:shadow-card active:scale-[0.99] dark:border-accent-light/30 dark:bg-accent-light/10"
          >
            <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-accent/15 text-accent dark:text-accent-light">
              <UserIcon className="h-5 w-5" />
            </span>
            <span className="flex-1 text-sm">
              <span className="font-semibold text-slate-800 dark:text-navy-50">
                プロフィールを設定
              </span>
              <span className="block text-xs text-slate-500 dark:text-navy-300">
                目標カロリー・PFC を計算します
              </span>
            </span>
            <span className="text-accent dark:text-accent-light" aria-hidden>
              →
            </span>
          </Link>
        )}

        {ready && dayMeals.length === 0 ? (
          <EmptyState />
        ) : (
          <div className="space-y-3">
            {dayMeals.map((meal) => (
              <MealCard
                key={meal.id}
                meal={meal}
                onEdit={() => setEditorState(meal)}
                onDelete={() => void removeMeal(meal.id)}
                onEat={
                  meal.status === "planned" ? () => handleEat(meal) : undefined
                }
                onGenerateImage={() => void handleGenerateImage(meal)}
                generatingImage={
                  generatingImageIds.has(meal.id) ||
                  hasPendingMealImageGeneration(mealImagePromptText(meal))
                }
                imageError={imageErrorIds.has(meal.id)}
                onGeneratedImageDataUrlBackfill={(generatedImageDataUrl, generatedImagePrompt) =>
                  updateGeneratedImageIfCurrent(meal.id, generatedImagePrompt, {
                    generatedImageDataUrl,
                    generatedImagePrompt,
                    generatedImageDataUrlFailedPrompt: undefined,
                    updatedAt: new Date().toISOString(),
                  })
                }
              />
            ))}
          </div>
        )}
      </div>

      {/* Floating add button */}
      <button
        type="button"
        onClick={() => setEditorState("new")}
        aria-label="食事を追加"
        className="group fixed bottom-24 right-1/2 z-20 flex h-14 w-14 translate-x-[calc(min(50vw,14rem)-1.5rem)] items-center justify-center rounded-full bg-gradient-to-br from-accent-light to-accent-dark text-white shadow-glow-accent transition duration-200 ease-spring hover:scale-105 hover:shadow-card-hover active:scale-95"
      >
        <PlusIcon className="h-7 w-7 transition-transform duration-300 ease-spring group-hover:rotate-90" />
      </button>

      {editorState !== null && (
        <MealEditor
          date={date}
          existing={editorState === "new" ? null : editorState}
          onClose={() => setEditorState(null)}
          onSave={handleSave}
        />
      )}
    </AppShell>
  );
}

function EmptyState() {
  return (
    <div className="flex animate-fade-in-up flex-col items-center justify-center rounded-2xl border border-dashed border-slate-200 px-6 py-16 text-center dark:border-navy-800">
      <span className="mb-3 flex h-14 w-14 items-center justify-center rounded-full bg-accent/10 text-accent dark:bg-accent-light/15 dark:text-accent-light">
        <MealIcon className="h-7 w-7" />
      </span>
      <p className="text-sm font-semibold text-slate-600 dark:text-navy-200">
        まだ記録がありません
      </p>
      <p className="mt-1 text-xs text-slate-400 dark:text-navy-400">
        右下の ＋ から写真かテキストで記録
      </p>
      <p className="mt-3 max-w-[18rem] text-xs leading-relaxed text-slate-400 dark:text-navy-400">
        記録のあと「<span className="font-semibold text-accent dark:text-accent-light">✨AI解析</span>」を押すと、カロリーと PFC が自動で出ます。
      </p>
    </div>
  );
}
