import type { Meal } from "@/lib/types";
import { isValidGeneratedMealImageDataUrl } from "./image";

export const MEAL_IMAGE_PROMPT_MAX_CHARS = 80;
export const MEALS_GENERATED_IMAGE_SYNC_MAX_COUNT = 12;
// Keep the synced meals blob safely UNDER the server's per-section size cap. The
// Worker (health-app-api validate.ts) rejects a section PUT with HTTP 400 when the
// blob's UTF-8 BYTE length exceeds MAX_DATA_BLOB_BYTES = 256*1024 (262,144 B). The
// prune budget MUST therefore be measured in BYTES on the same scale and sit well
// below that cap so a pruned blob always fits.
//
// (Bug fix: this was a 900,000-CHAR budget measured with String.length [UTF-16
// units]. 900k chars ≫ 262k bytes, so the prune effectively NEVER triggered before
// the server byte cap was hit — the meals blob grew with inline generatedImageDataUrl
// base64 until a save crossed 262,144 B, the PUT 400'd, and the failure was swallowed
// → meals silently stopped syncing across devices.)
export const MEALS_SYNC_MAX_JSON_BYTES = 240 * 1024; // 245,760 B < 262,144 B server cap

export interface MealCardImagePlan {
  hasUserPhoto: boolean;
  promptText: string;
  syncedImageSrc: string | null;
  legacyGeneratedImageId?: string;
  needsGeneratedImage: boolean;
  needsAutoGeneratedImage: boolean;
}

function capMealImagePrompt(prompt: string): string {
  return prompt.trim().replace(/\s+/g, " ").slice(0, MEAL_IMAGE_PROMPT_MAX_CHARS);
}

export function structuredMealImagePromptText(
  meal: Pick<Meal, "nutrition" | "recipe">,
): string {
  const names =
    meal.nutrition?.items
      ?.map((item) => item.name.trim())
      .filter(Boolean)
      .slice(0, 8) ?? [];
  if (names.length > 0) return capMealImagePrompt(names.join("、"));

  const ingredients =
    meal.recipe?.ingredients
      ?.map((ingredient) => ingredient.trim())
      .filter(Boolean)
      .slice(0, 8) ?? [];
  if (ingredients.length > 0) return capMealImagePrompt(ingredients.join("、"));

  return "";
}

export function mealImagePromptText(meal: Pick<Meal, "text" | "nutrition" | "recipe">): string {
  const structured = structuredMealImagePromptText(meal);
  if (structured) return structured;
  const firstLine =
    meal.text
      .split(/\r?\n/)
      .map((line) => line.trim())
      .find(Boolean) ?? "";
  const firstSentence = firstLine.split(/[。.!?！？]/)[0] ?? firstLine;
  return capMealImagePrompt(firstSentence);
}

export function hasFreshGeneratedMealImage(meal: Meal): boolean {
  const promptText = mealImagePromptText(meal);
  if (!promptText) return false;
  if (!isValidGeneratedMealImageDataUrl(meal.generatedImageDataUrl)) return false;
  return meal.generatedImagePrompt === promptText;
}

export function resolveMealCardImage(meal: Meal): MealCardImagePlan {
  const hasUserPhoto = Boolean(
    (meal.photoIds && meal.photoIds.length > 0) || meal.photoId,
  );
  const promptText = mealImagePromptText(meal);
  const syncedImageSrc = hasFreshGeneratedMealImage(meal)
    ? meal.generatedImageDataUrl!
    : null;
  const legacyGeneratedImageId =
    !syncedImageSrc &&
    promptText &&
    meal.generatedImagePrompt === promptText
      ? meal.generatedImageId
      : undefined;
  const autoRetrySuppressed = meal.generatedImageDataUrlFailedPrompt === promptText;
  const hasStructuredPrompt = Boolean(structuredMealImagePromptText(meal));

  return {
    hasUserPhoto,
    promptText,
    syncedImageSrc,
    legacyGeneratedImageId,
    needsGeneratedImage: Boolean(promptText && !syncedImageSrc),
    needsAutoGeneratedImage: Boolean(
      hasStructuredPrompt &&
        promptText &&
        !syncedImageSrc &&
        !legacyGeneratedImageId &&
        !autoRetrySuppressed,
    ),
  };
}

function stripGeneratedImageSyncFields(meal: Meal): Meal {
  return {
    ...meal,
    generatedImageDataUrl: undefined,
  };
}

/** UTF-8 byte length of a value's JSON form — the SAME unit the server's
 *  validateDataPayload uses for MAX_DATA_BLOB_BYTES, so the prune budget and the
 *  server cap are compared on the same scale (not UTF-16 char count). */
function jsonByteLength(value: unknown): number {
  return new TextEncoder().encode(JSON.stringify(value)).length;
}

export function pruneGeneratedMealImageDataUrls(meals: Meal[]): Meal[] {
  let next = meals.map((meal) => ({ ...meal }));
  const withGeneratedData = next
    .map((meal, index) => ({ meal, index }))
    .filter(({ meal }) => typeof meal.generatedImageDataUrl === "string")
    .sort((a, b) => b.meal.timestamp.localeCompare(a.meal.timestamp));
  const strip = new Set(
    withGeneratedData.slice(MEALS_GENERATED_IMAGE_SYNC_MAX_COUNT).map(({ index }) => index),
  );

  next = next.map((meal, index) =>
    strip.has(index) ? stripGeneratedImageSyncFields(meal) : meal,
  );

  for (const { index } of withGeneratedData.slice(0, MEALS_GENERATED_IMAGE_SYNC_MAX_COUNT).reverse()) {
    if (jsonByteLength(next) <= MEALS_SYNC_MAX_JSON_BYTES) break;
    next[index] = stripGeneratedImageSyncFields(next[index]);
  }

  return next;
}
