import { describe, expect, it } from "vitest";
import {
  hasFreshGeneratedMealImage,
  MEAL_IMAGE_PROMPT_MAX_CHARS,
  MEALS_GENERATED_IMAGE_SYNC_MAX_COUNT,
  mealImagePromptText,
  pruneGeneratedMealImageDataUrls,
  resolveMealCardImage,
  structuredMealImagePromptText,
} from "./mealCardImage";
import type { Meal } from "./types";

function meal(overrides: Partial<Meal>): Meal {
  return {
    id: "meal-1",
    date: "2026-06-27",
    timestamp: "2026-06-27T06:00:00.000Z",
    type: "朝",
    text: "ブラックコーヒー",
    ...overrides,
  };
}

describe("mealImagePromptText", () => {
  it("normalizes the menu prompt used for generated icons", () => {
    expect(mealImagePromptText(meal({ text: " 卵、  木綿豆腐\n鶏むね肉  " }))).toBe(
      "卵、 木綿豆腐",
    );
  });

  it("caps the generated image prompt so private notes and long text are not sent wholesale", () => {
    const prompt = mealImagePromptText(
      meal({
        text: `焼き芋。これは個人的なメモです\n${"長い".repeat(80)}`,
      }),
    );

    expect(prompt).toBe("焼き芋");
    expect(prompt.length).toBeLessThanOrEqual(MEAL_IMAGE_PROMPT_MAX_CHARS);
  });

  it("prefers structured food names over raw free-form meal text", () => {
    const prompt = mealImagePromptText(
      meal({
        text: "家族の体調メモ。焼き芋を食べた",
        nutrition: {
          calories: 113,
          items: [
            {
              id: "item-1",
              name: "焼き芋",
              grams: 100,
              qty: 1,
              kcal: 113,
              proteinG: 1,
              fatG: 0,
              carbG: 29,
              sourceKind: "db",
            },
          ],
        },
      }),
    );

    expect(prompt).toBe("焼き芋");
  });
});

describe("resolveMealCardImage", () => {
  it("uses a fresh synced generated icon as the card image", () => {
    const dataUrl = "data:image/webp;base64,SMALL";
    const plan = resolveMealCardImage(
      meal({
        generatedImageId: "generated-coffee",
        generatedImageDataUrl: dataUrl,
        generatedImagePrompt: "ブラックコーヒー",
      }),
    );

    expect(plan.syncedImageSrc).toBe(dataUrl);
    expect(plan.legacyGeneratedImageId).toBeUndefined();
    expect(plan.needsGeneratedImage).toBe(false);
  });

  it("keeps a same-prompt legacy generated id only as a temporary local display/backfill source", () => {
    const plan = resolveMealCardImage(
      meal({
        generatedImageId: "generated-coffee",
        generatedImagePrompt: "ブラックコーヒー",
      }),
    );

    expect(plan.hasUserPhoto).toBe(false);
    expect(plan.syncedImageSrc).toBeNull();
    expect(plan.legacyGeneratedImageId).toBe("generated-coffee");
    expect(plan.needsGeneratedImage).toBe(true);
    expect(plan.needsAutoGeneratedImage).toBe(false);
  });

  it("does not fall back to static template images for ungenerated foods", () => {
    const plan = resolveMealCardImage(meal({ text: "焼き芋" }));

    expect(plan.syncedImageSrc).toBeNull();
    expect(plan.legacyGeneratedImageId).toBeUndefined();
    expect(plan.needsGeneratedImage).toBe(true);
    expect(plan.needsAutoGeneratedImage).toBe(false);
  });

  it("does not let user photos suppress generated menu icons when structured food names exist", () => {
    const plan = resolveMealCardImage(
      meal({
        photoIds: ["photo-a"],
        text: "焼き芋",
        nutrition: {
          calories: 113,
          items: [
            {
              id: "item-1",
              name: "焼き芋",
              grams: 100,
              qty: 1,
              kcal: 113,
              proteinG: 1,
              fatG: 0,
              carbG: 29,
              sourceKind: "db",
            },
          ],
        },
      }),
    );

    expect(plan.hasUserPhoto).toBe(true);
    expect(plan.syncedImageSrc).toBeNull();
    expect(plan.legacyGeneratedImageId).toBeUndefined();
    expect(plan.needsGeneratedImage).toBe(true);
    expect(plan.needsAutoGeneratedImage).toBe(true);
  });

  it("treats a generated icon for old text as stale", () => {
    const stale = meal({
      text: "ゆでそば",
      generatedImageDataUrl: "data:image/webp;base64,OLD",
      generatedImagePrompt: "唐揚げ",
    });

    expect(hasFreshGeneratedMealImage(stale)).toBe(false);
    expect(resolveMealCardImage(stale).needsGeneratedImage).toBe(true);
  });

  it("treats promptless synced data URLs as stale so edited menus cannot keep old images", () => {
    const legacy = meal({ generatedImageDataUrl: "data:image/webp;base64,OLD" });

    expect(hasFreshGeneratedMealImage(legacy)).toBe(false);
    expect(resolveMealCardImage(legacy).needsGeneratedImage).toBe(true);
  });

  it("rejects oversized generated data URLs even when the prompt matches", () => {
    const oversized = "data:image/webp;base64," + "A".repeat(120_000);
    const plan = resolveMealCardImage(
      meal({
        generatedImageDataUrl: oversized,
        generatedImagePrompt: "ブラックコーヒー",
      }),
    );

    expect(plan.syncedImageSrc).toBeNull();
    expect(plan.needsGeneratedImage).toBe(true);
  });

  it("suppresses only automatic retries after thumbnail sync compression failed", () => {
    const plan = resolveMealCardImage(
      meal({
        generatedImageId: "generated-coffee",
        generatedImagePrompt: "ブラックコーヒー",
        generatedImageDataUrlFailedPrompt: "ブラックコーヒー",
      }),
    );

    expect(plan.syncedImageSrc).toBeNull();
    expect(plan.needsGeneratedImage).toBe(true);
    expect(plan.needsAutoGeneratedImage).toBe(false);
  });
});

describe("structuredMealImagePromptText", () => {
  it("returns an empty prompt for raw-text-only meals so auto generation stays explicit", () => {
    expect(structuredMealImagePromptText(meal({ text: "焼き芋" }))).toBe("");
  });
});

describe("pruneGeneratedMealImageDataUrls", () => {
  it("keeps synced generated thumbnails only for the most recent bounded set", () => {
    const meals = Array.from({ length: MEALS_GENERATED_IMAGE_SYNC_MAX_COUNT + 2 }, (_, index) =>
      meal({
        id: `meal-${index}`,
        timestamp: `2026-06-27T${String(index).padStart(2, "0")}:00:00.000Z`,
        generatedImageId: `generated-${index}`,
        generatedImageDataUrl: `data:image/webp;base64,IMG${index}`,
        generatedImagePrompt: "ブラックコーヒー",
      }),
    );

    const pruned = pruneGeneratedMealImageDataUrls(meals);
    const kept = pruned.filter((item) => item.generatedImageDataUrl);

    expect(kept).toHaveLength(MEALS_GENERATED_IMAGE_SYNC_MAX_COUNT);
    expect(pruned[0].generatedImageDataUrl).toBeUndefined();
    expect(pruned[0].generatedImageId).toBe("generated-0");
    expect(pruned.at(-1)?.generatedImageDataUrl).toBe(
      `data:image/webp;base64,IMG${MEALS_GENERATED_IMAGE_SYNC_MAX_COUNT + 1}`,
    );
  });
});
